# permissions for end users to edit gpunodepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gpunodepolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gpu-operator
    app.kubernetes.io/part-of: gpu-operator
    app.kubernetes.io/managed-by: kustomize
  name: gpunodepolicy-editor-role
rules:
- apiGroups:
  - ecns.easystack.com
  resources:
  - gpunodepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecns.easystack.com
  resources:
  - gpunodepolicies/status
  verbs:
  - get
