apiVersion: ecns.easystack.com/v1
kind: GpuNodePolicy
metadata:
  labels:
    app.kubernetes.io/name: gpunodepolicy
    app.kubernetes.io/instance: gpunodepolicy-sample
    app.kubernetes.io/part-of: gpu-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gpu-operator
  name: gpunodepolicy-sample
spec:
  # TODO(user): Add fields here
