//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	configv1 "github.com/NVIDIA/gpu-operator/apis/config/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSyncStatus) DeepCopyInto(out *ConfigSyncStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSyncStatus.
func (in *ConfigSyncStatus) DeepCopy() *ConfigSyncStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultModeStatus) DeepCopyInto(out *DefaultModeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultModeStatus.
func (in *DefaultModeStatus) DeepCopy() *DefaultModeStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultModeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodePolicy) DeepCopyInto(out *GpuNodePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodePolicy.
func (in *GpuNodePolicy) DeepCopy() *GpuNodePolicy {
	if in == nil {
		return nil
	}
	out := new(GpuNodePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuNodePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodePolicyList) DeepCopyInto(out *GpuNodePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GpuNodePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodePolicyList.
func (in *GpuNodePolicyList) DeepCopy() *GpuNodePolicyList {
	if in == nil {
		return nil
	}
	out := new(GpuNodePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuNodePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodePolicySpec) DeepCopyInto(out *GpuNodePolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VcudaConfig != nil {
		in, out := &in.VcudaConfig, &out.VcudaConfig
		*out = new(VcudaConfigSpec)
		**out = **in
	}
	if in.TimeSlicingConfig != nil {
		in, out := &in.TimeSlicingConfig, &out.TimeSlicingConfig
		*out = new(TimeSlicingConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MigConfig != nil {
		in, out := &in.MigConfig, &out.MigConfig
		*out = new(MigConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodePolicySpec.
func (in *GpuNodePolicySpec) DeepCopy() *GpuNodePolicySpec {
	if in == nil {
		return nil
	}
	out := new(GpuNodePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodePolicyStatus) DeepCopyInto(out *GpuNodePolicyStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]GpuNodeStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodePolicyStatus.
func (in *GpuNodePolicyStatus) DeepCopy() *GpuNodePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GpuNodePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodeStatus) DeepCopyInto(out *GpuNodeStatus) {
	*out = *in
	if in.TimeSlicingMode != nil {
		in, out := &in.TimeSlicingMode, &out.TimeSlicingMode
		*out = new(TimeSlicingModeStatus)
		**out = **in
	}
	if in.MigMode != nil {
		in, out := &in.MigMode, &out.MigMode
		*out = new(MigModeStatus)
		**out = **in
	}
	if in.DefaultMode != nil {
		in, out := &in.DefaultMode, &out.DefaultMode
		*out = new(DefaultModeStatus)
		**out = **in
	}
	if in.VcudaMode != nil {
		in, out := &in.VcudaMode, &out.VcudaMode
		*out = new(VcudaModeStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodeStatus.
func (in *GpuNodeStatus) DeepCopy() *GpuNodeStatus {
	if in == nil {
		return nil
	}
	out := new(GpuNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuSelector) DeepCopyInto(out *GpuSelector) {
	*out = *in
	if in.RootDevices != nil {
		in, out := &in.RootDevices, &out.RootDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuSelector.
func (in *GpuSelector) DeepCopy() *GpuSelector {
	if in == nil {
		return nil
	}
	out := new(GpuSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigConfigSpec) DeepCopyInto(out *MigConfigSpec) {
	*out = *in
	if in.ConfigSlice != nil {
		in, out := &in.ConfigSlice, &out.ConfigSlice
		*out = make([]MigConfigSpecSlice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigConfigSpec.
func (in *MigConfigSpec) DeepCopy() *MigConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MigConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigConfigSpecSlice) DeepCopyInto(out *MigConfigSpecSlice) {
	*out = *in
	if in.MigDevices != nil {
		in, out := &in.MigDevices, &out.MigDevices
		*out = make(configv1.MigConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigConfigSpecSlice.
func (in *MigConfigSpecSlice) DeepCopy() *MigConfigSpecSlice {
	if in == nil {
		return nil
	}
	out := new(MigConfigSpecSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigModeStatus) DeepCopyInto(out *MigModeStatus) {
	*out = *in
	out.DevicePlugin = in.DevicePlugin
	out.MigParted = in.MigParted
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigModeStatus.
func (in *MigModeStatus) DeepCopy() *MigModeStatus {
	if in == nil {
		return nil
	}
	out := new(MigModeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedResource) DeepCopyInto(out *ReplicatedResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedResource.
func (in *ReplicatedResource) DeepCopy() *ReplicatedResource {
	if in == nil {
		return nil
	}
	out := new(ReplicatedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingConfigSpec) DeepCopyInto(out *TimeSlicingConfigSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ReplicatedResource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingConfigSpec.
func (in *TimeSlicingConfigSpec) DeepCopy() *TimeSlicingConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingModeStatus) DeepCopyInto(out *TimeSlicingModeStatus) {
	*out = *in
	out.DevicePlugin = in.DevicePlugin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingModeStatus.
func (in *TimeSlicingModeStatus) DeepCopy() *TimeSlicingModeStatus {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingModeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcudaConfigSpec) DeepCopyInto(out *VcudaConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcudaConfigSpec.
func (in *VcudaConfigSpec) DeepCopy() *VcudaConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VcudaConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcudaModeStatus) DeepCopyInto(out *VcudaModeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcudaModeStatus.
func (in *VcudaModeStatus) DeepCopy() *VcudaModeStatus {
	if in == nil {
		return nil
	}
	out := new(VcudaModeStatus)
	in.DeepCopyInto(out)
	return out
}
